---
- name: fw input - accept dns requests from lan (udp)
  iptables:
    chain: INPUT
    source: 192.168.0.0/16
    protocol: udp
    destination_port: 53
    jump: ACCEPT
  become: true

- name: fw input - accept dns requests from lan (tcp)
  iptables:
    chain: INPUT
    source: 192.168.0.0/16
    protocol: tcp
    destination_ports:
      - 53
      - 853
    jump: ACCEPT
  become: true

- name: fw input - accept http from PCs
  iptables:
    chain: INPUT
    source: "{{ item }}"
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
  loop:
    - "{{ hostvars['tower'].ansible_host }}"
    - "{{ hostvars['laptop'].ansible_host }}"
  become: true