---
- name: Install nginx
  apt:
    name:
      - nginx
  become: true

- name: Sync nginx confs
  ansible.posix.synchronize:
    src: "{{ conf.nginx }}"
    dest: /etc/
  become: true
  notify: "restart nginx"

- name: Copy certificates
  copy:
    src: "{{ item }}"
    dest: "{{ www.cert }}/"
    force: true
  loop:
    - "{{ dist.cert }}/{{ cert.star_pem }}"
    - "{{ dist.cert }}/{{ cert.star_fc }}"
  become: true
  notify: "restart nginx"

- name: Sync cats site
  ansible.posix.synchronize:
    src: "{{ dist.cats }}"
    dest: "{{ www.cats }}"
  become: true
  notify: "restart nginx"

- name: fw input - accept all http/s
  iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
     - "80"
     - "443"
    jump: ACCEPT
  become: true

- name: fw input - accept response from vault
  iptables:
    chain: INPUT
    source: "{{ hostvars['vault'].ansible_host }}"
    protocol: tcp
    ctstate: ESTABLISHED,RELATED
    source_port: "{{ item }}"
    jump: ACCEPT
  loop:
   - "80"
   - "443"
   - "3012"
  become: true

- name: fw output - permit all http/s response
  iptables:
    chain: OUTPUT
    protocol: tcp
    source_port: "{{ item }}"
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  loop:
   - "80"
   - "443"
  become: true

- name: fw output - permit ssh response to pcs/ansible
  iptables:
    chain: OUTPUT
    destination: "{{ item }}"
    protocol: tcp
    source_port: 22
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  loop:
   - "{{ hostvars['tower'].ansible_host }}"
   - "{{ hostvars['laptop'].ansible_host }}"
   - "{{ hostvars['nexus'].ansible_host }}"
  become: true

- name: fw output - permit dns to pihole
  iptables:
    chain: OUTPUT
    destination: "{{ hostvars['pihole'].ansible_host }}"
    protocol: udp
    destination_port: 53
    jump: ACCEPT
  become: true

- name: fw output - permit proxy traffic to vault
  iptables:
    chain: OUTPUT
    destination: "{{ hostvars['vault'].ansible_host }}"
    protocol: tcp
    destination_ports:
     - "80"
     - "443"
     - "3012"
    jump: ACCEPT
  become: true

- name: fw output - permit icmp to lan
  iptables:
    chain: OUTPUT
    destination: 192.168.0.0/16
    protocol: icmp
    jump: ACCEPT
  become: true

- name: fw output - default drop
  iptables:
    chain: OUTPUT
    policy: DROP
  become: true