---
- name: install sudo
  apt:
    name: 
      - sudo
  when: ansible_user == "root"

- name: Create user
  user:
    name: "{{ setup_user }}"
    append: true
    groups: sudo
  become: true

- name: Enable passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ setup_user }}'
    line: '%{{ setup_user }} ALL=(ALL) NOPASSWD: ALL'
  become: true

- name: Create key directory
  file:
    path: /home/{{ setup_user }}/.ssh
    state: directory
  become: true

- name: Add public key
  copy:
    src: "{{ dist['keys'] }}/{{ setup_user }}"
    dest: '/home/{{ setup_user }}/.ssh/authorized_keys'
  become: true
  when: ansible_hostname != server['hub']