---
- name: install sudo
  apt:
    name: 
      - sudo
  when: ansible_user == "root"

- name: Create user
  user:
    name: "{{ setup_user }}"
    append: true
    groups: sudo
  become: true

- name: Enable passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ setup_user }}'
    line: '%{{ setup_user }} ALL=(ALL) NOPASSWD: ALL'
  become: true

- name: Create key directory
  file:
    path: /home/{{ setup_user }}/.ssh
    state: directory
  become: true

- name: Add public key (ansible user)
  ansible.posix.authorized_key:
    user: "{{ setup_user }}"
    state: present
    key: https://github.com/srsnowden.keys
  become: true
  when: setup_user == "sybil"

- name: Add public key (admin user)
  copy:
    src: '/home/{{ setup_user }}/.ssh/authorized_keys'
    dest: '/home/{{ setup_user }}/.ssh/authorized_keys'
  become: true
  when: setup_user != "sybil"  && ansible_hostname != "localhost"

- name: Restart ssh
  systemd:
    name: sshd
    state: restarted
  become: true