---
- name: Disable ssh password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item }}"
    line: PasswordAuthentication no
  become: true
  loop:
    - '^\#PasswordAuthentication*'
    - '^PasswordAuthentication*'
  notify: "restart sshd"

- name: Comment out root login setting
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item }}"
    line: '#PermitRootLogin prohibit-password'
  become: true
  loop:
    - '^\#PermitRootLogin*'
    - '^\PermitRootLogin*'
  notify: "restart sshd"

- name: Set allowed users - default
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      AllowUsers aragorn@{{ hostvars['tower'].ansible_host }}
      AllowUsers strider@{{ hostvars['laptop'].ansible_host }}
      AllowUsers sybil@{{ hostvars['nexus'].ansible_host }}
  become: true
  notify: "restart sshd"
  when: ansible_hostname not in groups["proxmox"]

- name: Set allowed users - proxmox default
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      AllowUsers root@{{ hostvars['boxy'].ansible_host }}
      AllowUsers aragorn@{{ hostvars['tower'].ansible_host }}
      AllowUsers strider@{{ hostvars['laptop'].ansible_host }}
      AllowUsers sybil@{{ hostvars['nexus'].ansible_host }}
  become: true
  notify: "restart sshd"
  when: ansible_hostname in groups["proxmox"] && ansible_hostname != {{ server.proxmain }}

- name: Set allowed users - proxmox cluster main
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      AllowUsers root@localhost
      AllowUsers aragorn@{{ hostvars['tower'].ansible_host }}
      AllowUsers strider@{{ hostvars['laptop'].ansible_host }}
      AllowUsers sybil@{{ hostvars['nexus'].ansible_host }}
  become: true
  notify: "restart sshd"
  when: ansible_hostname == {{ server.proxmain }}

- name: accept ssh from pcs/ansible
  iptables:
    chain: INPUT
    source: "{{ item }}"
    protocol: tcp
    destination: "{{ ansible_host }}"
    destination_port: 22
    in_interface: "{{ in_if | default(omit) }}"
    jump: ACCEPT
  loop:
    - "{{ hostvars['tower'].ansible_host }}"
    - "{{ hostvars['laptop'].ansible_host }}"
    - "{{ hostvars['nexus'].ansible_host }}"
  become: true