---
- name: Disable ssh password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item }}"
    line: PasswordAuthentication no
  become: true
  loop:
    - ^\#PasswordAuthentication*
    - ^PasswordAuthentication*
  notify: "restart sshd"

- name: Comment out root login setting
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item }}"
    line: '#PermitRootLogin prohibit-password'
  become: true
  loop:
    - ^\#PermitRootLogin*
    - ^PermitRootLogin*
  notify: "restart sshd"

- name: Set allowed users - default
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      AllowUsers aragorn@{{ hostvars['tower'].ansible_host }}
      AllowUsers strider@{{ hostvars['laptop'].ansible_host }}
      AllowUsers sybil@{{ hostvars['nexus'].ansible_host }}
    marker: "# {mark} DEFAULT SSH USERS"
  become: true
  notify: "restart sshd"

- name: Add allowed user - prox main
  import_tasks: proxmain.yml
  when: ansible_host == server.proxmain

- name: Add allowed user - prox default
  import_tasks: proxdefault.yml
  when:
    - inventory_hostname in groups['proxmox']
    - ansible_hostname != server.proxmain

- name: accept ssh from pcs/ansible
  iptables:
    chain: INPUT
    source: "{{ item }}"
    protocol: tcp
    destination: "{{ ansible_host }}"
    destination_port: 22
    in_interface: "{{ in_if | default(omit) }}"
    jump: ACCEPT
  loop:
    - "{{ hostvars['tower'].ansible_host }}"
    - "{{ hostvars['laptop'].ansible_host }}"
    - "{{ hostvars['nexus'].ansible_host }}"
  become: true