---
- name: Disable ssh password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: (^PasswordAuthentication*|^\#PasswordAuthentication*)
    line: PasswordAuthentication no
  become: true
  notify: "restart sshd"

- name: Comment out root login setting
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: (^PermitRootLogin*|^\#PermitRootLogin*)
    line: '#PermitRootLogin prohibit-password'
  become: true
  notify: "restart sshd"

- name: Set allowed users - default
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      AllowUsers aragorn@{{ hostvars['tower'].ansible_host }}
      AllowUsers strider@{{ hostvars['laptop'].ansible_host }}
      AllowUsers sybil@{{ hostvars['nexus'].ansible_host }}
    marker: "# {mark} DEFAULT SSH USERS"
  become: true
  notify: "restart sshd"

- name: Add root to allowed users - proxmox
  import_tasks: proxmox.yml
  when: inventory_hostname in groups['proxmox']

- name: accept ssh from pcs/ansible
  iptables:
    chain: INPUT
    source: "{{ item }}"
    protocol: tcp
    destination_port: 22
    in_interface: "{{ in_if | default(omit) }}"
    jump: ACCEPT
  loop:
    - "{{ hostvars['tower'].ansible_host }}"
    - "{{ hostvars['laptop'].ansible_host }}"
    - "{{ hostvars['nexus'].ansible_host }}"
  become: true