---
- name: Set allowed user - prox default
  blockinfile:
    path: /etc/ssh/sshd_config
    block: AllowUsers root@{{ hostvars['boxy'].ansible_host }}
    marker: "# {mark} PROXMOX SSH USER"
  become: true
  when: ansible_hostname != server.proxmain
  notify: "restart sshd"

- name: Set allowed user - prox main
  blockinfile:
    path: /etc/ssh/sshd_config
    block: AllowUsers root@localhost
    marker: "# {mark} PROXMOX SSH USER"
  become: true
  when: ansible_hostname == server.proxmain
  notify: "restart sshd"

- name: fw input - allow ssh from prox hosts
  iptables:
    chain: INPUT
    source: "{{ item }}"
    protocol: tcp
    source_port: 22
    jump: ACCEPT
  loop:
    - "{{ hostvars['boxy'].ansible_host }}"
    - "{{ hostvars['cubey'].ansible_host }}"
  become: true