---
- name: Install pacakages
  apt:
    name:
      - syncthing
  become: true

- name: enable syncthing service
  service:
    name: syncthing@aragorn.service
    enabled: yes
  become: true

- name: start syncthing service
  service:
    name: syncthing@aragorn.service
    state: started
  become: true