---
- name: Install pacakages
  apt:
    name:
      - syncthing
  become: true

- name: enable syncthing service
  service:
    name: syncthing@aragorn.service
    enabled: yes
  become: true

- name: start syncthing service
  service:
    name: syncthing@aragorn.service
    state: started
  become: true

- name: change GUI address
  lineinfile:
    path: /home/aragorn/.config/syncthing/config.xml
    regexp: "{{ item.match }}"
    line: "{{ item.paste }}"
  become: true
  loop:
    - { match: '^        \<address', paste: '        <address>0.0.0.0:8384</address>' }
    - { match: '^    <gui', paste: '    <gui enabled="true" tls="true" debugging="false">' }
  notify: restart syncthing

- name: copy https certs
  copy:
    src: "{{ item.from }}"
    dest: "{{ item.to }}"
    owner: aragorn
    group: aragorn
    mode: 0600
  loop:
    - { from: '{{ dist.cert }}/{{ cert.star_pem }}', to: '/home/aragorn/.config/syncthing/https-key.pem'}
    - { from: '{{ dist.cert }}/{{ cert.star_fc }}', to: '/home/aragorn/.config/syncthing/https-cert.pem'}
  become: true

- name: accept syncthing tcp traffic
  iptables:
    chain: INPUT
    source: 192.168.0.0/24
    protocol: tcp
    destination_ports:
      - 8384
      - 22000
    in_interface: "{{ in_if | default(omit) }}"
    jump: ACCEPT
  become: true

- name: accept syncthing udp traffic
  iptables:
    chain: INPUT
    source: 192.168.0.0/24
    protocol: udp
    destination_port: 22000
    in_interface: "{{ in_if | default(omit) }}"
    jump: ACCEPT
  become: true