---
- name: Install samba
  apt:
    name:
      - samba
  become: true

- name: Create public share user
  user:
    name: "{{ share.pubuser }}"
    shell: /sbin/nologin
    create_home: no
  become: true

- name: Create private share user
  user:
    name: "{{ share.archuser }}"
    password: "{{ share.archpass }}"
    shell: /sbin/nologin
    create_home: no
  become: true

- name: Chown share directories to share users
  file:
    path: "{{ item.dir }}"
    state: directory
    recurse: yes
    owner: "{{ item.usr }}"
    group: "{{ item.grp }}"
  loop:
    - { dir: "{{ share.pubdir }}", usr: "{{ share.pubuser }}", grp: "{{ share.pubuser }}" }
    - { dir: "{{ share.archdir }}", usr: "{{ share.archuser }}", grp: "{{ share.archuser }}" }
    - { dir: "{{ share.proxdir }}", usr: "{{ share.archuser }}", grp: "{{ share.archuser }}" }
  become: true

- name: Create samba user - public share
  shell: "smbpasswd -n -a {{ share.pubuser }}"
  become: true

- name: Create samba user - private share
  vars:
    gandalf_pw: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      34643763383962343434383637393637343561633133376466346533373564316533336239386139
      3835386331303734666337313335353263393066623235620a326261623366633062623764396238
      65646634306130353563633631373934323231313666633935326431393236623431663335326636
      6135656663653261660a656635373538316137306338383434653562343838363233356637333337
      6139
  shell: "(echo {{ gandalf_pw }}; echo {{ gandalf_pw }}) | smbpasswd -s -a {{ share.archuser }}"
  become: true

- name: Update samba config - global settings
  blockinfile:
    path: /etc/samba/smb.conf
    insertafter: '\[global\]'
    marker: "# {mark} ANSIBLE GLOBAL CONFIG"
    block: |
     null passwords = yes
     interfaces = eth0
     bind interfaces only = yes
     netbios aliases = share, archive, proxstore
  notify: "restart smbd"
  become: true

- name: Update samba config - share settings
  blockinfile:
    path: /etc/samba/smb.conf
    marker: "# {mark} ANSIBLE SHARE CONFIG"
    block: |
      [share]
          path = {{ share.pubdir }}
          writable = yes
          printable = no
          public = yes
          create mask = 0777
          directory mask = 0777
          force user = {{ share.pubuser }}
          force group = {{ share.pubuser }}

      [archive]
          path = {{ share.archdir }}
          writable = yes
          printable = no
          public = no
          create mask = 0777
          directory mask = 0777
          valid user = {{ share.archuser }}

      [backups]
          path = {{ share.proxdir }}/backups
          writable = yes
          printable = no
          public = no
          create mask = 0777
          directory mask = 0777
          valid user = {{ share.archuser }}

      [templates]
          path = {{ share.proxdir }}/templates
          writable = yes
          printable = no
          public = no
          create mask = 0777
          directory mask = 0777
          valid user = {{ share.archuser }}
  notify: "restart smbd"
  become: true