---
- name: Install samba
  apt:
    name:
      - samba
  become: true

- name: Create public share user
  user:
    name: "{{ share.pubuser }}"
    shell: /sbin/nologin
    create_home: no
  become: true

- name: Create private share user
  user:
    name: "{{ share.archuser }}"
    password: "{{ share.archpass }}"
    shell: /sbin/nologin
    create_home: no
  become: true

- name: Chown share directories to share users
  file:
    path: "{{ item.dir }}"
    state: directory
    recurse: yes
    owner: "{{ item.usr }}"
    group: "{{ item.grp }}"
  loop:
    - { dir: "{{ share.pubdir }}", usr: "{{ share.pubuser }}", grp: "{{ share.pubuser }}" }
    - { dir: "{{ share.archdir }}", usr: "{{ share.archuser }}", grp: "{{ share.archuser }}" }
    - { dir: "{{ share.proxdir }}", usr: "{{ share.archuser }}", grp: "{{ share.archuser }}" }
  become: true

- name: Create samba user - public share
  shell: "smbpasswd -n -a pippin"
  become: true

- name: Create samba user - private share
  vars:
    gandalf_pw: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      34643763383962343434383637393637343561633133376466346533373564316533336239386139
      3835386331303734666337313335353263393066623235620a326261623366633062623764396238
      65646634306130353563633631373934323231313666633935326431393236623431663335326636
      6135656663653261660a656635373538316137306338383434653562343838363233356637333337
      6139
  shell: "(echo {{ gandalf_pw }}; echo {{ gandalf_pw }}) | smbpasswd -s -a gandalf"
  become: true