---
- name: Set cronjob - renew certificate
  cron:
    name: "renew certificate"
    minute: 0
    hour: 4
    day: 1
    month: "*/2"
    job: "/home/aragorn/.local/bin/ansible-playbook /repos/serenity/playbooks/cert-star.yml"