---
- name: install sudo
  apt:
    name: 
      - sudo
  when: ansible_user == "root"

- name: Create ansible user
  user:
    name: "{{ setup_user }}"
    append: true
    groups: sudo
  become: true

- name: Enable passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ setup_user }}'
    line: '%{{ setup_user }} ALL=(ALL) NOPASSWD: ALL'
  become: true

- name: Create key directory for ansible user
  file:
    path: /home/{{ setup_user }}/.ssh
    state: directory
  become: true

- name: Add ansible user public key
  ansible.posix.authorized_key:
    user: "{{ setup_user }}"
    state: present
    key: https://github.com/srsnowden.keys
  become: true

- name: Restart ssh
  systemd:
    name: sshd
    state: restarted
  become: true