---

- hosts: palantir

  tasks:
    - name: set default policy - accept all
      iptables:
        chain: "{{ item }}"
        policy: ACCEPT
      loop:
       - "INPUT"
       - "FORWARD"
       - "OUTPUT"
      become: true

    - name: flush existing rules
      iptables:
        chain: "{{ item }}"
        flush: yes
      loop:
       - "INPUT"
       - "FORWARD"
       - "OUTPUT"
      become: true

    - name: accept ssh from pcs/ansible
      iptables:
        chain: INPUT
        source: "{{ item }}"
        protocol: tcp
        destination_port: 22
        jump: ACCEPT
      loop:
       - "{{ hostvars['tower'].ansible_host }}"
       - "{{ hostvars['laptop'].ansible_host }}"
       - "{{ hostvars['nexus'].ansible_host }}"
      become: true

    - name: accept all http/s
      iptables:
        chain: INPUT
        protocol: tcp
        destination_ports:
         - "80"
         - "443"
        jump: ACCEPT
      become: true

    - name: accept dns from pihole
      iptables:
        chain: INPUT
        source: "{{ hostvars['pihole'].ansible_host }}"
        protocol: udp
        source_port: 53
        jump: ACCEPT
      become: true

    - name: accept proxy response from vault
      iptables:
        chain: INPUT
        source: "{{ hostvars['vault'].ansible_host }}"
        protocol: tcp
        ctstate: ESTABLISHED,RELATED
        source_port: "{{ item }}"
        jump: ACCEPT
      loop:
       - "80"
       - "443"
       - "3012"
      become: true

    - name: accept local icmp
      iptables:
        chain: INPUT
        source: 192.168.0.0/16
        protocol: icmp
        jump: ACCEPT
      become: true

    - name: default input policy - drop
      iptables:
        chain: INPUT
        policy: DROP
      become: true

    - name: permit response - all http/s
      iptables:
        chain: OUTPUT
        protocol: tcp
        source_port: "{{ item }}"
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
      loop:
       - "80"
       - "443"
      become: true

    - name: permit response - ssh from pcs/ansible
      iptables:
        chain: OUTPUT
        destination: "{{ item }}"
        protocol: tcp
        source_port: 22
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
      loop:
       - "{{ hostvars['tower'].ansible_host }}"
       - "{{ hostvars['laptop'].ansible_host }}"
       - "{{ hostvars['nexus'].ansible_host }}"
      become: true

    - name: permit dns to pihole
      iptables:
        chain: OUTPUT
        destination: "{{ hostvars['pihole'].ansible_host }}"
        protocol: udp
        destination_port: 53
        jump: ACCEPT
      become: true

    - name: permit vault proxy traffic
      iptables:
        chain: OUTPUT
        destination: "{{ hostvars['vault'].ansible_host }}"
        protocol: tcp
        destination_ports:
         - "80"
         - "443"
         - "3012"
        jump: ACCEPT
      become: true

    - name: permit local icmp
      iptables:
        chain: OUTPUT
        destination: 192.168.0.0/16
        protocol: icmp
        jump: ACCEPT
      become: true

    - name: default output policy - drop
      iptables:
        chain: OUTPUT
        policy: DROP
      become: true