---

- hosts: localhost

  tasks:
    - name: Set hostname
      hostname:
        name: nexus

    - name: Update host file
      lineinfile:
        path: /etc/hosts
        line: '127.0.0.1    nexus'
      become: true

    - name: Disable ssh password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item }}"
        line: PasswordAuthentication no
      loop:
        - '^\#PasswordAuthentication*'
        - '^PasswordAuthentication*'
      become: true

    - name: Create ansible directory
      file:
        path: /etc/ansible
        state: directory

    - name: Sync /etc/ansible
      ansible.posix.synchronize:
        src: /repos/serenity/config/ansible/
        dest: /etc/ansible/
      become: true