- name: Send cats update
  community.general.mail:
    host: "{{ hostvars['mail'].ansible_host }}"
    password: "{{ webmeowster_pw }}"
    username: webmeowster@spencers.house
    sender: 'Humphrey & Annabelle <webmeowster@spencers.house>'
    subtype: html
    port: 587
    to: ''
    bcc:
      - srsnowden@gmail.com
      - awsnowden@gmail.com
    subject: New pics!
    body: |
      Some new pictures have been added to <a href="https://cats.spencers.house">https://cats.spencers.house</a> - hope you enjoy!
      <br><br><br><br>
      <p style="font-size:0.8em">This is an automated update message.  To be removed from future updates (and potentially hurt Annabelle and/or Humphrey's feelings) simply reply to this message.</p>