- name: Send cats update
  community.general.mail:
    host: "{{ hostvars['mail'].ansible_host }}"
    password: "{{ webmeowster_pw }}"
    username: webmeowster@spencers.house
    sender: 'Humphrey & Annabelle <webmeowster@spencers.house>'
    subtype: html
    port: 587
    to: ''
    bcc:
      - srsnowden@gmail.com
    subject: New pictures!
    body: 'New pictures have been added to <a href="https://cats.spencers.house">https://cats.spencers.house</a>.  Enjoy!'