---

- hosts: palantir

  remote_user: aragorn

  tasks:
    - name: Set hostname
      hostname:
        name: palantir
        become: true

    - name: Update host file
      lineinfile:
        path: /etc/hosts
        line: '127.0.0.1    palantir'
        become: true

    - name: Disable ssh password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item }}"
        line: PasswordAuthentication no
        become: true
      loop:
        - '^\#PasswordAuthentication*'
        - '^PasswordAuthentication*'

    - name: Create key directory for admin user
      file:
        path: /home/aragorn/.ssh
        state: directory
        become: true

    - name: Copy public key for admin user
      copy:
        src: /home/aragorn/.ssh/authorized_keys
        dest: /home/aragorn/.ssh/authorized_keys
        become: true

    - name: Create ansible user
      user:
        name: sybil
        append: true
        groups: sudo
        become: true

    - name: Create key directory for ansible user
      file:
        path: /home/sybil/.ssh
        state: directory
        become: true

    - name: Add ansible user public key
      ansible.posix.authorized_key:
        user: sybil
        state: present
        key: https://github.com/srsnowden.keys
        become: true