---

- hosts: localhost

  roles:
    - role: cert
      cert_cn: "*.spencers.house"
      cert_name: star.spencers.house
      pkcs12: create

- hosts: palantir
  
  roles:
    - role: d_proxycert

- hosts: media

  roles:
    - role: d_mediacert

- hosts: localhost

  tasks:
    - name: Set cronjob - renew certificate
      cron:
        name: "renew certificate"
        minute: 0
        hour: 4
        day: 1
        month: "*/2"
        job: "/home/aragorn/.local/bin/ansible-playbook /repos/serenity/playbooks/cert-star.yml"