---

- hosts: palantir

  tasks:
    - name: Install packages
      apt:
        name:
          - nginx
      become: true

    - name: Copy nginx confs
      copy:
        src: /repos/serenity/config/palantir/nginx/
        dest: /etc/nginx/
      become: true

    - name: Sync nginx data directory
      ansible.posix.synchronize:
        src: ~/dist/data/
        dest: /data/
      become: true