---

- hosts: localhost

  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: nexus

    - name: Install vlan
      ansible.builtin.apt:
        name: vlan

    - name: Add vlan file
      copy:
        dest: /etc/network/interfaces.d/vlans
        content: |
          auto eth0.20
          iface eth0.20 inet manual
            vlan-raw-device eth0

          auto eth0.30
          iface eth0.30 inet manual
            vlan-raw-device eth0

          auto eth0.40
          iface eth0.40 inet manual
            vlan-raw-device eth0

    - name: Update dhcpcd.conf
      blockinfile:
        path: /etc/dhcpcd.conf
        block: |
          interface eth0
          static ip_address=192.168.10.20/24
          static routers=192.168.10.1
          static domain_name_servers=192.168.10.100

          interface eth0.20
          static ip_address=192.168.20.5/24
          static routers=192.168.20.1
          static domain_name_servers=192.168.10.100

          interface eth0.30
          static ip_address=192.168.30.5/24
          static routers=192.168.30.1
          static domain_name_servers=192.168.10.100

          interface eth0.40
          static ip_address=192.168.40.5/24
          static routers=192.168.40.1
          static domain_name_servers=192.168.10.100

    - name: Mount external drive
      ansible.posix.mount:
        path: /mnt/ark01
        src: LABEL=ark01
        fstype: ext4
        state: mounted

    - name: Add public share user
      user:
        name: pippin
        password: $6$8OT8wX1XbUwuIKvt$bS8a6t7Ljn9TasjFCcTFnYgevSblpNbclg.cSenXs41rY/uCN37MVBF/nrG8SAwax0H4zBsAJlirc9nk93.MO/
        shell: /sbin/nologin
        create_home: no

    - name: Change share permissions to user
      file:
        path: /mnt/ark01/share
        state: directory
        recurse: yes
        owner: pippin
        group: pippin

    - name: Install samba
      apt:
        name: samba

    - name: Update samba config
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [share]
          path = /mnt/ark01/share
          writable = yes
          printable = no
          public = yes
          create mask = 0777
          directory mask = 0777
          valid users = pippin
          force user = pippin
          force group = pippin

    - name: Create samba user
      shell: "(echo breakfast; echo breakfast) | smbpasswd -s -a pippin"
      become: true

    - name: Restart samba service
      systemd:
        state: restarted
        name: samba