---

- hosts: localhost

  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: nexus

    - name: Update host file
      lineinfile:
        path: /etc/hosts
        line: '127.0.0.1    nexus'

    - name: Pull authorized keys from git
      ansible.posix.authorized_key:
        user: aragorn
        state: present
        key: "{{ lookup('url', 'https://github.com/srsnowden.keys', split_lines=False) }}"

    - name: Disable ssh password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^\#PasswordAuthentication yes'
        line: PasswordAuthentication no

    - name: Install vlan
      ansible.builtin.apt:
        name: vlan

    - name: Update vlans config - add vlans for mdns repeater
      copy:
        dest: /etc/network/interfaces.d/vlans
        content: |
          auto eth0.20
          iface eth0.20 inet manual
            vlan-raw-device eth0

          auto eth0.30
          iface eth0.30 inet manual
            vlan-raw-device eth0

          auto eth0.40
          iface eth0.40 inet manual
            vlan-raw-device eth0

    - name: Update dhcpcd config - add static addresses
      blockinfile:
        path: /etc/dhcpcd.conf
        block: |
          interface eth0
          static ip_address=192.168.10.20/24
          static routers=192.168.10.1
          static domain_name_servers=192.168.10.100

          interface eth0.20
          static ip_address=192.168.20.5/24
          static routers=192.168.20.1
          static domain_name_servers=192.168.10.100

          interface eth0.30
          static ip_address=192.168.30.5/24
          static routers=192.168.30.1
          static domain_name_servers=192.168.10.100

          interface eth0.40
          static ip_address=192.168.40.5/24
          static routers=192.168.40.1
          static domain_name_servers=192.168.10.100

    - name: Mount external drive
      ansible.posix.mount:
        path: /mnt/ark01
        src: LABEL=ark01
        fstype: ext4
        state: mounted
 
    - name: Add public share user
      user:
        name: pippin
        shell: /sbin/nologin
        create_home: no

    - name: Chown share directories to share user
      file:
        path: "{{ item }}"
        state: directory
        recurse: yes
        owner: pippin
        group: pippin
      loop:
        - /mnt/ark01/share
        - /mnt/ark01/proxstore
        - /mnt/ark01/archive

    - name: Install samba
      apt:
        name: samba

    - name: Update samba config - global settings
      blockinfile:
        path: /etc/samba/smb.conf
        insertafter: '\[global\]'
        marker: "# {mark} ANSIBLE GLOBAL CONFIG"
        block: |
         null passwords = yes
         interfaces = eth0
         bind interfaces only = yes


    - name: Update samba config - share settings
      blockinfile:
        path: /etc/samba/smb.conf
        marker: "# {mark} ANSIBLE SHARE CONFIG"
        block: |
          [share]
              path = /mnt/ark01/share
              writable = yes
              printable = no
              public = yes
              create mask = 0777
              directory mask = 0777
              force user = pippin
              force group = pippin

          [archive]
              path = /mnt/ark01/archive
              writable = yes
              printable = no
              public = yes
              create mask = 0777
              directory mask = 0777
              force user = pippin
              force group = pippin

          [backups]
              path = /mnt/ark01/proxstore/backups
              writable = yes
              printable = no
              public = yes
              create mask = 0777
              directory mask = 0777
              force user = pippin
              force group = pippin

          [templates]
              path = /mnt/ark01/proxstore/templates
              writable = yes
              printable = no
              public = yes
              create mask = 0777
              directory mask = 0777
              force user = pippin
              force group = pippin

    - name: Create samba user - public share
      shell: "smbpasswd -n -a pippin"
      become: true

    - name: Restart samba service
      systemd:
        state: restarted
        name: smbd

    - name: Update avahi config - enable mdns reflector
      lineinfile:
        path: /etc/avahi/avahi-daemon.conf
        regexp: '^\#enable-reflector=no'
        line: enable-reflector=yes

    - name: Restart avahi service
      systemd:
        state: restarted
        name: avahi-daemon