---

- hosts: palantir

  tasks:
    - name: Install packages
      apt:
        name:
          - nginx
      become: true

    - name: Copy nginx confs
      copy:
        src: /repos/serenity/config/palantir/nginx/
        dest: /etc/nginx/
      become: true
      notify: "restart nginx"

    - name: Copy certificates
      copy:
        src: "{{ item }}"
        dest: /data/keys/
      loop:
        - /dist/keys/star.spencers.house.pem
        - /dist/keys/star.spencers.house-fullchain.crt
      become: true

    - name: Sync cats site
      ansible.posix.synchronize:
        src: /dist/cats
        dest: /data/
      become: true
      notify: "restart nginx"
  
  handlers:
    - name: restart nginx
      systemd:
        name: nginx
      become: true