---

- hosts: palantir

  vars:
    ansible_user: aragorn

  tasks:
    - name: Set hostname
      hostname:
        name: {{ ansible_hostname }}

    - name: Update host file
      lineinfile:
        path: /etc/hosts
        line: '127.0.0.1    {{ ansible_hostname }}'
      become: true

    - name: Disable ssh password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item }}"
        line: PasswordAuthentication no
      become: true
      loop:
        - '^\#PasswordAuthentication*'
        - '^PasswordAuthentication*'

    - name: Create users - ansible and laptop
      user:
        name: "{{ item }}"
        append: true
        groups: sudo
      loop:
        - sybil
        - strider
      become: true

    - name: Enable passwordless sudo - ansible and laptop
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "{{ item.search }}"
        line: "{{ item.replace }}"
      loop:
        - { search: '^%sybil', replace: '%sybil ALL=(ALL) NOPASSWD: ALL' }
        - { search: '^%strider', replace: '%strider ALL=(ALL) NOPASSWD: ALL' }
      become: true

    - name: Create key directory for all users
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /home/aragorn/.ssh
        - /home/sybil/.ssh
        - /home/strider/.ssh
      become: true

    - name: Copy local public keys
      copy:
        src: "{{ item.from }}"
        dest: "{{ item.to }}"
      loop:
        - { from: '/home/aragorn/.ssh/authorized_keys', to: '/home/aragorn/.ssh/authorized_keys' }
        - { from: '/home/strider/.ssh/authorized_keys', to: '/home/strider/.ssh/authorized_keys' }
      become: true

    - name: Add ansible user public key
      ansible.posix.authorized_key:
        user: sybil
        state: present
        key: https://github.com/srsnowden.keys
      become: true

    - name: Restart ssh service
      systemd:
        state: restarted
        name: sshd
      become: true