---

- hosts: palantir

  remote_user: aragorn

  tasks:
    - name: Set hostname
      hostname:
        name: palantir

    - name: Update host file
      lineinfile:
        path: /etc/hosts
        line: '127.0.0.1    palantir'

    - name: Disable ssh password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item }}"
        line: PasswordAuthentication no
      loop:
        - '^\#PasswordAuthentication*'
        - '^PasswordAuthentication*'

    - name: Copy public key for admin user
      copy:
        src: /home/aragorn/.ssh/authorized_keys
        dest: /home/aragorn/.ssh/authorized_keys

    - name: Create ansible user
      user:
        name: sybil
        append: true
        groups: sudo

    - name: Add ansible user public key
      ansible.posix.authorized_key:
        user: sybil
        state: present
        key: https://github.com/srsnowden.keys