---

- hosts: localhost

  tasks:
    - name: set default policy - accept all
      iptables:
        chain: "{{ item }}"
        policy: ACCEPT
      loop:
       - "INPUT"
       - "FORWARD"
       - "OUTPUT"
      become: true

    - name: flush existing rules
      iptables:
        chain: "{{ item }}"
        flush: yes
      loop:
       - "INPUT"
       - "FORWARD"
       - "OUTPUT"
      become: true

    - name: accept ssh from pcs
      iptables:
        chain: INPUT
        source: "{{ item }}"
        destination: "{{ hostvars['nexus'].ansible_host }}"
        protocol: tcp
        destination_port: 22
        in_interface: eth0
        jump: ACCEPT
      loop:
       - "{{ hostvars['tower'].ansible_host }}"
       - "{{ hostvars['laptop'].ansible_host }}"
      become: true

    - name: accept smb from secure & laptop
      iptables:
        chain: INPUT
        source: "{{ item }}"
        destination: "{{ hostvars['nexus'].ansible_host }}"
        protocol: tcp
        destination_ports:
        - "139"
        - "445"
        in_interface: eth0
        jump: ACCEPT
      loop:
       - 192.168.10.0/16
       - "{{ hostvars['laptop'].ansible_host }}"
      become: true

    - name: accept mDNS traffic on all interfaces
      iptables:
        chain: INPUT
        source: 192.168.0.0/16
        protocol: udp
        destination_port: 5353
        jump: ACCEPT
      become: true

    - name: allow related and established connections
      iptables:
        chain: INPUT
        destination: "{{ hostvars['nexus'].ansible_host }}"
        ctstate: ESTABLISHED,RELATED
        in_interface: eth0
        jump: ACCEPT
      become: true

    - name: default drop policy
      iptables:
        chain: INPUT
        policy: DROP
      become: true

  handlers: