---

- hosts: localhost

  tasks:
    - name: flush existing rules
      iptables:
        chain: INPUT
        flush: yes
      become: true

    - name: accept mDNS traffic on all interfaces
      iptables:
        chain: INPUT
        source: 192.168.0.0/16
        protocol: udp
        destination_port: 5353
        jump: ACCEPT
      become: true

  handlers: