---

- hosts: localhost

  tasks:
    - name: flush existing rules
      iptables:
        chain: INPUT
        flush: yes
      become: true

    - name: accept limited ssh
      iptables:
        chain: INPUT
        source: "{{ item }}"
        destination: "{{ hostvars['nexus'].ansible_host }}"
        protocol: tcp
        destination_port: 22
        jump: ACCEPT
      loop:
       - "{{ hostvars['tower'].ansible_host }}"
       - "{{ hostvars['laptop'].ansible_host }}"
      become: true


    - name: accept mDNS traffic on all interfaces
      iptables:
        chain: INPUT
        source: 192.168.0.0/16
        protocol: udp
        destination_port: 5353
        jump: ACCEPT
      become: true

  handlers: