---

- hosts: localhost

  tasks:
    - name: Git pull
      git:
        repo: git@github.com:srsnowden/serenity.git
        dest: /repos/serenity
        key_file: "{{ ansible_ssh_private_key_file }}"
      become: true

    - name: Sync /etc/ansible
      ansible.posix.synchronize:
        src: /repos/serenity/config/ansible/
        dest: /etc/ansible/
      become: true