---

- hosts: localhost

  gather_facts: no

  vars_prompt:
    - name: username
      prompt: Enter user name
      private: false

    - name: userpass
      prompt: Enter password
      private: true

- hosts: test

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ userpass }}"

  tasks:   
    - name: Include sybil role
      include_role:
        name: sybil

- hosts: test

  tasks:
    - name: Print ansible user
      debug:
        msg: "{{ ansible_user }}"