---

- hosts: localhost

  tasks:
    - name: Set hostname
      hostname:
        name: nexus

    - name: Update host file
      lineinfile:
        path: /etc/hosts
        line: '127.0.0.1    nexus'
      become: true

    - name: Disable ssh password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item }}"
        line: PasswordAuthentication no
      loop:
        - '^\#PasswordAuthentication*'
        - '^PasswordAuthentication*'
      become: true

    - name: Create ansible directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /etc/ansible
        - /etc/ansible/group_vars

    - name: Update /etc/ansible
      copy:
        src: /repos/serenity/config/ansible/
        dest: /etc/ansible/
      become: true