---

- hosts: localhost

  tasks:
    - name: Add public share user
      user:
        name: merry
        shell: /sbin/nologin
        create_home: no

    - name: Change share permissions to user
      file:
        path: /mnt/ark01/share
        state: directory
        recurse: yes
        owner: merry
        group: merry

    - name: Update samba config
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [share]
          path = /mnt/ark01/test
          writable = yes
          printable = no
          public = yes
          create mask = 0777
          directory mask = 0777
          force user = merry
          force group = merry

    - name: test samba update
      lineinfile:
        path: /etc/samba/smb.conf
        insertafter: '\[global\]'
        line: 'null passwords = yes'

    - name: Create samba user
      shell: "smbpasswd -a -n merry"
      become: true

    - name: Restart samba service
      systemd:
        state: restarted
        name: smbd