---

- hosts: localhost

  tasks:

    - name: Send test mail
      community.general.mail:
        host: "{{ hostvars['mail'].ansible_host }}"
        password: DRCYrAyM^Lt$9e
        username: webmeowster@spencers.house
        port: 587
        to: srsnowden@gmail.com
        subject: Hello pt. 2
        body: Hello from ansible