---

- hosts: localhost

  tasks:
    - name: accept syncthing tcp traffic
      iptables:
        chain: INPUT
        source: 192.168.0.0/24
        protocol: tcp
        destination_ports:
          - 8384
          - 22000
        in_interface: eth0
        jump: ACCEPT
      become: true

    - name: accept syncthing udp traffic
      iptables:
        chain: INPUT
        source: 192.168.0.0/24
        protocol: udp
        destination_ports:
          - 22000
          - 21027
        in_interface: eth0
        jump: ACCEPT
      become: true