---

- hosts: mail

  tasks:

    - name: Send test mail
      community.general.mail:
        host: localhost
        port: 587
        username: webmeowster
        password: DRCYrAyM^Lt$9e
        to: srsnowden@gmail.com
        subject: Hello pt. 2
        body: Hello from ansible