---

- hosts: localhost

  tasks:

    - name: Send test mail
      community.general.mail:
        host: "{{ hostvars['mail'].ansible_host }}"
        password: "{{ webmeowster_pw }}"
        username: webmeowster@spencers.house
        sender: 'Spencer''s Cats <webmeowster@spencers.house>'
        subtype: html
        port: 587
        bcc: srsnowden@gmail.com
        subject: Hello pt. 5
        body: '<a href="https://cats.spencers.house">cats.spencers.house</a> has been updated with new pictures'