---
- name: fw input - accept dns from pihole
  iptables:
    chain: INPUT
    source: "{{ hostvars['pihole'].ansible_host }}"
    protocol: udp
    source_port: 53
    in_interface: "{{ in_if | default(omit) }}"
    jump: ACCEPT
  become: true

- name: fw input - accept icmp from lan
  iptables:
    chain: INPUT
    source: 192.168.0.0/16
    protocol: icmp
    in_interface: "{{ in_if | default(omit) }}"
    jump: ACCEPT
  become: true

- name: fw input - accept established, related
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    in_interface: "{{ in_if | default(omit) }}"
    jump: ACCEPT
  when: ansible_hostname != server.proxy
  become: true

- name: Add default proxmox rules
  import_tasks: proxmox.yml
  when: inventory_hostname in groups['proxmox']

- name: fw input - default drop
  iptables:
    chain: INPUT
    policy: DROP
  become: true