---
- name: Install pacakages
  apt:
    name:
      - avahi
      - vlan
  become: true

- name: Update vlans config - add vlans for mdns repeater
  copy:
    dest: /etc/network/interfaces.d/vlans
    content: |
      auto eth0.20
      iface eth0.20 inet manual
        vlan-raw-device eth0

      auto eth0.30
      iface eth0.30 inet manual
        vlan-raw-device eth0

      auto eth0.40
      iface eth0.40 inet manual
        vlan-raw-device eth0
  become: true

- name: Update dhcpcd config - add static addresses
  blockinfile:
    path: /etc/dhcpcd.conf
    block: |
      interface eth0
      static ip_address=192.168.10.20/24
      static routers=192.168.10.1
      static domain_name_servers=192.168.10.100

      interface eth0.20
      static ip_address=192.168.20.5/24
      static routers=192.168.20.1
      static domain_name_servers=192.168.10.100

      interface eth0.30
      static ip_address=192.168.30.5/24
      static routers=192.168.30.1
      static domain_name_servers=192.168.10.100

      interface eth0.40
      static ip_address=192.168.40.5/24
      static routers=192.168.40.1
      static domain_name_servers=192.168.10.100
  become: true

- name: Update avahi config - enable mdns reflector
  lineinfile:
    path: /etc/avahi/avahi-daemon.conf
    regexp: (^\#enable-reflector=*|^enable-reflector=*)
    line: enable-reflector=yes
  notify: "restart avahi-daemon"
  become: true

- name: accept mDNS traffic on all interfaces
  iptables:
    chain: INPUT
    source: 192.168.0.0/16
    protocol: udp
    destination_port: 5353
    jump: ACCEPT
  become: true